# -*- coding: utf-8 -*-
"""Python For Research - Day 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7X4WLJX4-OeQrwki5HuqT88YPeKjOtL

# Day - 5

# Dictionary in Python
"""

a = {
    "apple" : "apple is a fruit",
    "ball" : "ball is played"
}

"""``` python
{
    key:value
}
```
"""

type(a)

num = {
    1: "one",
    2: "two",
    2.5 : "two",
    3 : "three",
    4: 4,
    5: [88, 77, 9]
}

type(num)

country = {
    "Nepal": "Kathmandu",
    "India": "New Delhi",
    "China": "Beijing"
}

type(country)

"""## accessing the values of a dictionary key"""

country["Nepal"]

country.get("Nepal")

"""## update or add key value pair in dictionary."""

country = {
    "Nepal": "Kathmandu",
    "India": "New Delhi",
    "China": "Beijing"
}

country['Pakistan'] = 'Islamabad'

country

country.update({'Bhutan': 'thimpu'})

country

country.update({'Bhutan': "Thimpu"})

country

"""# List key and values of a dictionary"""

c = {'Nepal': 'Kathmandu',
 'India': 'New Delhi',
 'China': 'Beijing',
 'Pakistan': 'Islamabad',
 'Bhutan': 'Thimpu'}

c.keys()

list(c.keys())

c.values()

list(c.values())

"""# removing key value pair in dictionary"""

c = {'Nepal': 'Kathmandu',
 'India': 'New Delhi',
 'China': 'Beijing',
 'Pakistan': 'Islamabad',
 'Bhutan': 'Thimpu'}

c.pop('China')

c

"""# Looping in Dictionary"""

c = {'Nepal': 'Kathmandu',
 'India': 'New Delhi',
 'China': 'Beijing',
 'Pakistan': 'Islamabad',
 'Bhutan': 'Thimpu'}

c.items()      # unpacking of tuple items: key, value

a, b = (5, 6)
print(a)
print(b)        # key, value.     a and b are keys while 5 and 6 are values. a corresponds to 5 and 6 corresponds to b.

for item in c:
    print(item)

for item in c:
    print(c.get(item))

for item in c:
    print("The key is {}".format(item))
    
    print("The value is {}".format(c.get(item)))

"""# Nested Dictionary"""

childrens = {
    'child1': {'name': "John", 'age' : 28},
    'child2': {'name': "Andy", 'school': 'boston'},
    'child3': {'name': "Andrew", 'gender':'M'}
}

childrens['child3']['gender']

childrens['child2']['gender']

childrens.get('child3').get('gender')

"""# Functions in Python"""

# classic method
a = 20

b = 8

c = a+b

print(c)

# defining function
def add():
    a = 20
    b = 8
    c = a + b
    print(c)

# calling the function
add()

add()   # i can call the function any number of times i want

"""### some dude sent in the meeting
```
s = "Hsenid"
for i in range(len(s)-1, -1, -1):
    print(s[i])
```
"""

def add(a,b):   # a , b are arguments given by the user
    c = a + b
    print(c)

add(7, 3)

add(5, 8)

"""# WAP to add two numbers and square the total sum."""

def add(a, b):
    c = a + b
    return c

total = add(6, 14)

total ** 2

def greet(name, msg):
    print("Hello {} , {}".format(name, msg))

greet("Nirajan", "Good Morning")

greet("Ram", "Good Morning")

"""# Default argument in python

"""

def greet(name, msg = "Good Morning"):
    print("Hello {} , {}".format(name, msg))

greet("Nirajan")

greet("Nirajan", "Good Evening")

