# -*- coding: utf-8 -*-
"""Assignment - 4 - Python For Research.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QqRyVvmkK5GhR01D2sVIQWTzr8h-F0s0

# Assignment - 4

## Python For Research

# 1. 1. Calculate mean using the range() method
scores = [20, 22, 59, 49, 27, 0, 62, 40, 58, 92, 36, 63, 75, 50, 73, 7, 49, 82, 1, 79]
"""

scores = [20, 22, 59, 49, 27, 0, 62, 40, 58, 92, 36, 63, 75, 50, 73, 7, 49, 82, 1, 79]

# Calculate the mean
mean = sum(scores) / len(scores)

# Print the mean
print(mean)     # The output is 45.15 and the program rounds off the value.

"""# 2. Sort the following number in reverse order:

numbers = [9, -5, 0, -12, 12,13,15,1,2,13]
"""

numbers = [9, -5, 0, -12, 12,13,15,1,2,13]
numbers.sort(reverse=True)
print(numbers)    # the function sorts through descending order in reverse.

"""# Write a program that stores squares(from 1 to 10)  of numbers in a list."""

squares = []
for i in range(1, 11):
    squares.append(i ** 2)

print(squares)

"""# 4. WAP to the lowercase item in the given list using list comprehension
fruits = ["APPLE", "BANANA", "MANGO", "ORANGE"]
"""

fruits = ["APPLE", "BANANA", "MANGO", "ORANGE"]

print([x.lower() for x in fruits])

"""# 5. Accept only numbers lower than 5 from -5 to 10. Use If condition on list comprehension."""

# list comprehension

numbers = [number for number in range(-5, 10) if number < 5]
print(numbers)

# list comprehension with if condition

numbers = [number for number in range(-5, 10) if number < 5 and number > -5]
print(numbers)