# -*- coding: utf-8 -*-
"""Python for Research - Day 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfxLaVznvFtTDtGA2w1NmFZXLgrEzcN6

# Day - 4 - Python For Research

# Python List



```
Collection of items under a particular variable
```
"""

fruits = ['apple', 'orange', 'banana', 'mango']

type(fruits)

"""#Indexing in Python List"""

fruits[0]
fruits[2]

"""# Negative Indexing"""

-len(fruits)

fruits[-3]

"""For Loop"""

for index in range(len(fruits)):
    name = fruits[index]
    print(name)

for item in fruits:
    print(item)

"""for item in iterables:
    pass

for index in range(start, end, step):
    pass

# While Loop

Could be runned infinite times

while True:
    # block of while code
"""

fruits = ['apple', 'orange', 'banana', 'mango']
i = 0
while i < len(fruits):

    print(fruits[i])
    i = i + 1

cars = ['Audi', 'BMW', 'Tesla', 'Maruti']

cars[2:]     # slicing

cars[:3]    # slicing

cars[2:4]    # slicing

"""# Calculate the mean of the follwing list"""

scores = [20, 22, 59, 49, 27, 0, 62, 40, 58, 92, 36,  63, 75, 50, 73, 7, 49, 42, 1, 79]

total = 0

for item in scores:
    total = total + item

mean = total / len(scores)
print("Mean = {}".format(mean))

"""# Membership Operator"""

cars = ['Audi', 'BMW', 'Tesla', 'Maruti']

"BMW" in cars

"Mercedes" in cars

"Mercedes" not in cars

"""# list operation"""

fruits = ['apple', 'banana', 'mango', 'orange', 'pear']

fruits[1] = "kiwi"    # list are mutable. You can modify value inside the list.

fruits

fruits = ['apple', 'banana', 'mango', 'orange', 'pear']

fruits[0:2] =['papaya', 'kiwi']
print(fruits)



"""# Insert method in python list"""

fruits = ['apple', 'banana', 'mango', 'orange', 'pear']
# We can add items in the list while we do it in our classic world. 
# apple
# papaya
# banana
# mango
fruits.insert(1, "papaya")

fruits

"""# Append() method of python list"""

a =[]
a.append(45)
print(a)

a.append(99)
print(a)

# We cannot add many items in the append function
a.append([44, 55, 66])

a

len(a)

a[2][1]

"""# remove() in python list"""

fruits = ['apple', 'banana', 'papaya', 'mango']
fruits.remove('apple')

fruits

fruits = ['apple', 'banana', 'papaya', 'mango']
fruits.pop()

fruits

fruits = ['apple', 'banana', 'papaya', 'mango']
fruits.pop(1)

fruits

"""# Sorting in Python List"""

nums =[4, -2, 55, 99, 0, -11]

nums.sort()

nums    # output in ascending order

nums =[4, -2, 55, 99, 0, -11]
nums.sort(reverse = True)

nums     # outputs in descending order

"""## Assignment for string"""

fruits = ['apple', 'banana', 'papaya', 'mango']
fruits.sort()

fruits

"""# List Comprehension"""

nums = [3, 4, 5, 11, 6]

sq = []
for item in nums:
    sq.append(item ** 2)

sq

"""# Syntax for List comprehension
## [expression for item in iterables]
"""

[item ** 2 for item in nums]

"""## Assignment: Read about if else in list comprehension"""

fruits = ['APPLE', 'BANANA', 'MANGO', 'PAPAYA', 'CHERRY', 'PEAR']

[items.lower() for items in fruits]

"""# tuples"""

# tuples are immutable.
# Read-only

data = ['Nirajan', 5343093, True, 22.5]

data

data = list(data)

"""# NoneType"""

x = None
type(x)

# None is a data type of its own (NoneType) and only None can be None.

x = None

x is None

x is not float

if x == None:
    print("x is none")

if x is None:
    print("x is none")

x = 5
5 is x