# -*- coding: utf-8 -*-
"""Assignment -3 - Python For Research.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HL7Q8qyE5-84G82PzR4thgKcqyUmN9P
"""

# We use GPU from GOOGLE cloud

"""# Assignment -3
# Day -3
# Python For Research

# 1. Using the string manipulation technique, Extract the fruit's name from the text.



```
txt = "I Like Orange Apple Banana and Kiwi."
['orange', 'apple', 'Banana', 'Kiwi']
```
"""

txt = 'I Like Orange Apple Banana and Kiwi'
text = txt.lower()        # lowercasing the given string
words = text.split()      # Splitting the words

last_index = len(words)
words

words[2]      # Extracts third word from the given string
words[3]      # Extracts fourth word from the given string
words[4]      # Extracts fifth word from the given string
words[6]      # Extracts seventh word from the given string

print("[ '{}' , '{}', '{}', '{}' ]".format(words[2], words[3], words[4], words[6]))

"""# 2. WAP to count vowels and consonants on the given string."""

txt = input("Enter a string: ")
vowels = 0
consonants = 0

for i in txt:
    if i in "aeiouAEIOU":
        vowels += 1
    elif i in "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ":
        consonants += 1

print("Vowels: ", vowels)
print("Consonants: ", consonants)

"""# 3. Read a string from the user and print it in the reverse order using the loops and range() function."""

# Read a string from the user
string = input("Enter a string: ")

# Print the string in reverse order
for i in range(len(string) - 1, -1, -1):
    print(string[i], end="")

"""# 4. Python Program to display the table of 7."""

list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for i in list:
    print("7 x ", i , " = ", i * 7)

"""# 5. Python Program to convert temperature in celsius to Fahrenheit."""

celsius = float(input("Enter the temperature in celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("The temperature in fahrenheit is: ", fahrenheit)