# -*- coding: utf-8 -*-
"""Assignment - 2 - Python For Research.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKGAeTmUIaoQDvSFWCx9hz2latkOBngh

# ASSIGNMENT -2  PYTHON FOR RESEARCH

# 1. Write a program to check if the given input is 10 or not. If it is 10 print the number else print input is not 10
"""

# Ask the user to input a number.
n = int(input("Enter a number : "))
if n == 10:
    print("The Number is Ten.")
else:
    print("The Number is not Ten.")

"""# 2. WAP to check whether the user-given input integer is a positive or negative Number. If it is positive print the square of the number else prints the cube of the user-given input."""

# Ask the user to input a number.
n = int(input("Enter a number : "))

# Applying the conditions: if the user-defined value is positive, print the square of the number, else print the cube of the user-input value.
if n > 0:
    a = n**2
    print("The Number is positive, and the square of the number", n , "is : ", a)
else:
    b = n**3
    print("The Number is negative, and the cube of the number", n , "is :", b)

"""# 3.  Write a program to display "Hello" if a number entered by the user is a multiple of five,  otherwise print "Bye"."""

n = int(input("Ente a number : "))
if n % 5 == 0:
    print("Hello!")
else:
    print("Bye")

"""# 4. Write a program to check whether the last digit of a number ( entered by the user ) is divisible by 3 or not."""

num=int(input("Enter a number:"))
last_digit = num % 10     # this gives the last number as remainder
if(last_digit % 3 == 0):  # Applying the conditions:
    print("{} is divisible by 3 ".format(last_digit))
else:
    print("{} is not divisible by 3".format(last_digit))

"""# 5. The volume of a sphere with radius r is 4/3 π r3. What is the volume of a sphere with a radius of 5?"""

# inporting math module
import math
# The variable for radius is assigned to r.
r = 5
vol = ((4/3) * math.pi * r ** 3)
print ('The volume of a sphere is: ', vol)

"""# 6. WAP to Find the Largest Among Three Numbers"""

# Program to Find the Greatest Number Among Three Numbers.

# Creating three variables 'a', 'b', 'c', asking the values and storing three numbers separately in the variables.

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = int(input("Enter the third number: "))

if (a > b) and (a > c):
   largest = a
elif (b > a) and (b > c):
   largest = b
else:
   largest = c

print("The biggest number is: ", largest)

"""# 7. A school has the following rules for the grading system:

*   Below 25 - F
*   25 to 45 - E
*   45 to 50 - D
*   50 to 60 - C
*   60 to 80 - B
*   80 or Above 80 - A

Ask the user to enter marks and print the corresponding grade.
"""

print("Enter the student details below : ")

name = input("Enter the name of a student :  ")
grade = int(input("Enter the class of the student : "))
roll_no = int(input("Enter the roll number of the student : "))

print("Enter the marks obtained by the student below for the following subjects:")
# Entering the marks for the subjects. The subjects include English, Nepali, Mathematics, Physics, Chemistry, Computer, Social Studies and Life Skills.
Eng = float(input("English : "))
Nep = float(input("Nepali : "))
Math = float(input("Mathematics : "))
Phy = float(input("Physics : "))
Chem = float(input("Chemistry : "))
Comp = float(input("Computer : "))
Soc = float(input("Social Studies : "))
Lski = float(input("Life Skills : "))

# Adding the marks of all the subjects. Creating a variable called 'total' for summation of marks of subjects.
total = Eng+Nep+Math+Phy+Chem+Comp+Soc+Lski
# Creating a variable called 'avg' to calculate the average of total marks.
avg = total/8

# Processing The Output
print("Name: ", name)

print("Grade: ", grade)

print("Roll no: ", roll_no)

print("The marks obtained in the examination are: ")

print("English : ", Eng)
print("Nepali : ", Nep)
print("Mathematics : ", Math)
print("Physics : ", Phy)
print("Chemistry : ", Chem)
print("Computer : ", Comp)
print("Social Studies : ", Soc)
print("Life Skills : ", Lski)
print("The Total Marks Secured: ", total)


if avg > 80:
    print("Your Grade is A")
elif avg>=60 and avg<80:
    print("Your Grade is B")
elif avg>=50 and avg<60:
    print("Your Grade is C")
elif avg>=45 and avg<50:
    print("Your Grade is D")
elif avg>=25 and avg<45:
    print("Your Grade is E")
elif avg<25:
    print("Your grade is F")
else:
    print("Invalid Input!")

"""# 8. A company decided to give a bonus of 5% to the employee if his/her year of service is more than 5 years.

Ask the users for their salary and year of service and print the net bonus amount.
"""

salary = eval(input("Enter your salary:"))  
# eval() allows you to evaluate arbitrary Python expressions from a string-based or compiled-code-based input.
#This function can be handy when you're trying to dynamically evaluate Python expressions from any input that comes as a string 
# or a compiled code object.

service_years = eval(input("Enter Years of service:"))

if service_years > 5:

    print("Yours salary(+Bonus) = ",salary + (salary)*(service_years/100))

else:

     print("You are not eligible for bonus as you have less service years.")